# GraphQL Config

projects:
  default:
    schemaPath: https://docs.github.com/public/fpt/schema.docs.graphql
    documents: "src/**/*.{graphql,js,ts,jsx,tsx}"

    extensions:
      endpoints:
        default:
          url: https://api.github.com/graphql
          headers:
            Authorization: Bearer ${GITHUB_TOKEN}
